### ISSUE TITLE
Toys Guix Channel Search

### ISSUE THREAD

**Issue by jgarte** [Tass0sm/tassos-guix#1]
Hi fellow Guixer,

Would you be interested in joining our Guix channel search engine?

https://toys.whereis.みんな/

If so, send a patch here adding your channel:

https://git.sr.ht/~whereiseveryone/toys#join

**Comment by Tass0sm** [comment]
Thank you very much for the invitation! I'll get started on this now

**Comment by jgarte** [comment]
Awesome! Keep us posted.

all best,

jgart

https://whereis.みんな/
